version: "3.8"

services:
  nginx:
    container_name: nginx
    build:  requirements/nginx
    ports:
      - 443:443
    volumes:
      - website-volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception-network
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build:  requirements/wordpress
    ports:
      - 9000:9000
    volumes:
      - website-volume:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception-network

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception-network
  

  # nginx:
  # container_name: nginx
  # build: requirements/nginx
  # ports:
  #   - 443:443
  # volumes:
  #   - wordpress-volume:/var/lib/mysql
volumes:
  data-volume:
    name: data-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/tweimer/Documents/Docker/Inception2/data/data_base
  
  website-volume:
    name: website-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/tweimer/Documents/Docker/Inception2/data/wp
networks:
  inception-network:
    