#!/bin/bash
mysql_install_db;
mkdir /run/mysqld;
chmod 777 /run/mysqld;

/usr/bin/mysqld --user=mysql --bootstrap << EOF
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;
USE $DATABASE_NAME;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$MYSQL_USER'@'%';
CREATE USER IF NOT EXISTS '$SECOND_USER'@'%' IDENTIFIED BY '$SECOND_USER_PASSWORD';
FLUSH PRIVILEGES;
EOF

/usr/bin/mysqld;